version: 2

updates:

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "monthly"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-patch"]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-patch"]
