version: 2
builds:
  - env:
      - CGO_ENABLED=0
    id: "irir"
    binary: irir
    goos:
      - linux
      - darwin
      - windows
    ldflags: -s -w -X main.version={{.Version}} -X "main.installFrom=Binary"
archives:
  - format_overrides:
      - goos: windows
        format: zip
changelog:
  use: github
  filters:
    exclude:
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
brews:
  - repository:
      owner: bayashi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    license: "MIT"
    directory: Formula
    homepage: https://github.com/bayashi/irir
    description: A filter to add colors for text lines generically from a YAML configuration file easily
    test: |
      system "#{bin}/irir", '--version'