---
gotest:
- type: prefix
  match: "--- PASS"
  color: green
  target: line
- type: prefix
  match: "ok"
  color: green
  target: line
- type: prefix
  match: "PASS"
  color: green
  target: line
- type: prefix
  match: "--- FAIL"
  color: red
  target: line
- type: prefix
  match: "FAIL"
  color: bg_red
  target: line
- type: prefix
  match: "--- SKIP"
  color: dark_yellow
  target: line
- type: match
  match: "=== RUN"
  color: gray
  target: line
- target: line
  type: match
  match: "=== CONT"
  color: gray
- type: match
  match: "=== PAUSE"
  color: gray
  target: line
- type: match
  match: "[no tests to run]"
  color: yellow
  target: word
- type: match
  match: "[no test files]"
  color: yellow
  target: word
- type: regexp
  match: '[^\/]+\.go:\d+'
  color: cyan
  target: word
- type: match
  match: "Test name:"
  color: yellow
  target: line
- type: match
  match: "Expected:"
  color: green
  target: line
- type: match
  match: "Actually got:"
  color: cyan
  target: line
- type: match
  match: "Fail reason:"
  color: red
  target: line
