name: staticcheck

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:  ["ubuntu-latest"]
        go:  ["1.21"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup go${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: go get .

      - name: Run vet
        run: go vet -v ./...

      - name: Check diff of goimports
        run: |
            go install golang.org/x/tools/cmd/goimports@latest
            goimports -w . && git diff --exit-code

      - name: Setup staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2023.1.6"
          install-go: false
          min-go-version: ${{ matrix.go }}
          cache-key: ${{ matrix.os }}-${{ matrix.go }}

      - name: Run staticcheck
        run: staticcheck ./...
